name: HACS Validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hacs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
